
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage:delegated
      - ./bootstrap/cache:/var/www/bootstrap/cache:delegated
    env_file:
      - .env
    networks:
      - slack-archive
    depends_on:
      - db
      - redis

  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - slack-archive
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: slack_archive
      POSTGRES_USER: slack_user
      POSTGRES_PASSWORD: slack_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - slack-archive

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - slack-archive

volumes:
  postgres_data:

networks:
  slack-archive:
    driver: bridge
